apiVersion: v1
kind: Service
metadata:
  name: v2
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "v2"
    port: 8080
  - name: "ng"
    port: 4000
  - name: "web"
    port: 80
  selector:
    app: v2
